//
//  APIError.swift
//  Strivacity
//
//  Copyright (c) 2022 Strivacity <opensource@strivacity.com>
//

import Foundation

/**
 * Complete list of errors that can be generated by the API
 */
enum APIError: Error {
    
    /// Default error, means that something unexpected happens.
    case unexpectedError
    
    /// Error generates when the token exchange request can't be obtained from last authorization response.
    case failedToObtainTokenExchangeRequestFromLastAuthorizationResponse
    
    /// Error generates when some of the logout components (logout url, auth endpoint, token endpoint, id token) can't be obtained.
    case failedToObtainLogoutComponents
    
    /// Error indicates that OIDExternalUserAgentIOS object can't be created.
    case failedToCreateExternalUserAgent
    
    /// Error generates when URL object can't be created from passed redirectUri string.
    case failedToObtainRedirectUri
    
    /// Error generates when the OIDServiceConfiguration can't be obtained using AppAuth framework.
    case failedToDiscoverConfiguration
    
    /// Generates when the URL object can't be created from the passed domain string.
    case failedToCreateDomainUrlFromConfig
    
    /// Generates when the request url can't be obtained from OIDAuthorizationRequest object.
    case failedToObtainRequestUrl
    
    /// Generates when the hybrid flow request can't be present because the app is under guided access mode.
    case failedToRunAuthSessionAppIsUnderGuidedAccessMode //
    
    /// Generates when the OIDAuthorizationSession object can't be created with the passed OIDAuthorizationRequest.
    case failedToCreateAuthorizationSession
    
    /// Generates when the URL object can't be created with the string after replacing # to ? inside it.
    case failedToModifyUrl
    
    /// Generates when the id token string passed inside validation function is invalid.
    case failedToUnwrapIdTokenString
    
    /// Generates when the token structure is invalid (the token string doesn't have two dots, so it can't be splitted on header, payload and signature).
    case wrongTokenStructure
    
    /// Generates when the id token header is wrong and can't be parsed.
    case failedToParseIdTokenHeader
    
    /// Generates when the id token payload is wrong and can't be parsed.
    case failedToParseIdTokenPayload
    
    /// Generates when the id token header key id property isn't equal to the key id property obtained from jwksUrl
    case keyIdsAreDifferentError
    
    /// Generates when the id token payload is invalid.
    case failedToValidateIdTokenPayload
    
    /// Generates when the public key can't be created from the modulus and exponent obtained via jwls url.
    case failedToCreatePublicKey
    
    /// Generates when the authorization code is invalid, based on validation via cHash property stored in payload.
    case failedToValidateAuthCode
    
    /// Generates when the data from jwks url can't be obtained.
    case failedToObtainDataFromJwksUrl
    
    /// Generates when the json object can't be created with the data obtained from jwks url.
    case failedToCreateJsonFromJwksUrlData
    
    /// Generates when there is no object with proper key id and algorithm properties among objects obtained from jwks url data.
    case failedToFindObjectWithProperKeyId
    
    /// Generates when the json configuration of the obtained from jwks url dictionary is unexpected.
    case unexpectedJsonConfiguration
    
    /// Generates when the dictionary is invalid and can't be unwrapped.
    case failedToUnwrapDictionary
    
    /// Generates when the authorization response is invalid and can't be unwrapped.
    case failedToUnwrapAuthResponse
    
    /// Generates when the jwks url is invalid and can't be unwrapped.
    case failedToUnwrapJwksUrl
    
    /// Generates when the biometricManager object is invalid, it means that its creation failed.
    case biometricManagerCreationFailure
    
    /// Generates when the user specifies biometric usage on device that doesn't support such authentication.
    case biometricIsNotSupportedError
    
    /// Generates when the biometric authentication error is occured.
    case biometricAuthenticationError
}
