# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'Strivacity-usage-example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Strivacity-usage-example
  pod 'Strivacity', :git => 'https://github.com/Strivacity/sdk-mobile-ios.git'

end
